// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqbmEe7c3rRcsZfM7ZraBSEUGsiM81PE',
    appId: '1:853838256967:web:b6433793c6609f024cca62',
    messagingSenderId: '853838256967',
    projectId: 'mytask-586b4',
    authDomain: 'mytask-586b4.firebaseapp.com',
    storageBucket: 'mytask-586b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBED5_KoDqeeZt715Wyw_5UscVIY33JWJQ',
    appId: '1:853838256967:android:ad5619d88940be684cca62',
    messagingSenderId: '853838256967',
    projectId: 'mytask-586b4',
    storageBucket: 'mytask-586b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDHN0nJWsUvOuVzUgoqBxILVfU5Pu1nGc',
    appId: '1:853838256967:ios:6f2de2ea00b6abaf4cca62',
    messagingSenderId: '853838256967',
    projectId: 'mytask-586b4',
    storageBucket: 'mytask-586b4.appspot.com',
    iosClientId:
        '853838256967-b1oh0dijbvk0djcqtmsv5s0t5j6adehd.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDHN0nJWsUvOuVzUgoqBxILVfU5Pu1nGc',
    appId: '1:853838256967:ios:3bdfb3ad0de077134cca62',
    messagingSenderId: '853838256967',
    projectId: 'mytask-586b4',
    storageBucket: 'mytask-586b4.appspot.com',
    iosClientId:
        '853838256967-6ds7hlire5ch81r0t1jp10hh6dsm8arh.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTask.RunnerTests',
  );
}
